apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gcpuser1/argocd-appsets
        revision: HEAD
        files:
          - path: appproject-chart/values.yaml
  template:
    metadata:
      name: "{{tenants.name}}-app"
    spec:
      project: "{{tenants.name}}"
      source:
        repoURL: "{{tenants.repo}}"
        targetRevision: HEAD
        path: manifests
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{tenants.namespacePrefix}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
