apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gcpuser1/argocd-appsets
        revision: HEAD
        files:
          - path: tenants/*.yaml
  template:
    metadata:
      name: "{{name}}-app"
    spec:
      project: "{{name}}"
      source:
        repoURL: "{{repo}}"
        targetRevision: HEAD
        path: manifests
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespacePrefix}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
