apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appprojects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gcpuser1/argocd-appsets
    targetRevision: HEAD
    path: appproject-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
