tenants:
  - name: payments
    repos:
      - https://github.com/gcpuser1/payments-gitops
    namespacePrefix: payments
  - name: accounts
    repos:
      - https://github.com/gcpuser1/accounts-gitops
    namespacePrefix: accounts
